name: Build & Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Create secrets.dart
      - name: Create secrets.dart
        run: |
          mkdir -p lib/secrets
          cat > lib/secrets/secrets.dart <<EOF
          const String GEMINI_API_KEY = '${{ secrets.GEMINI_API_KEY }}';
          const String GOOGLE_MAP_API_KEY = '${{ secrets.GOOGLE_MAP_API_KEY }}';
          EOF

      # Setup Flutter from .fvmrc
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: .fvmrc
          cache: true

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: "17"

      # Verify versions
      - name: Flutter Version
        run: flutter --version

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build Android APK
      - name: Build Android APK
        run: flutter build apk --release --split-per-abi

      # Upload GitHub Release
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/apk/release/*
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}